# Generated by Django 6.0.3 on 2026-03-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produits',
            old_name='priice',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='produits',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
